runtime: php55
# threadsafe: true
# api_version: '2'

instance_class: F1


inbound_services:
# [START mail_service]
- mail
- mail_bounce
- warmup

runtime_config:
  document_root: web




handlers:
- url: /
  script: /index.html
 
- url: /index.html
  script: index.html

- url: /about-us.html
  script: about-us.html

- url: /candidate-services.html
  script: candidate-services.html 
 
- url: /contact-us.html
  script: contact-us.html  

- url: /business-services.html
  script: business-services.html



- url: /(.*)\.html$
  static_files: /\1.html
  upload: /*\.html$

- url: /contact-process.php
  script: contact-process.php

- url: /images
  static_dir: images

- url: /static
  static_dir: static

- url: /logo
  static_dir: logo
  

- url: /vendor/autoload.php
  script: vendor/autoload.php  

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
  
- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /_ah/mail/.+
  script: handle_incoming_email.php
  login: admin

error_handlers:
  - file: default_error.html

  - error_code: over_quota
    file: over_quota.html

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 10
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: trainomart2@appspot.gserviceaccount.com